In [1]:
import torch as t

### Example 1:-

In [2]:
#Intialization
x = t.rand(1,requires_grad=True)
print(x)
y = x**2
print(y)

tensor([0.9884], requires_grad=True)
tensor([0.9769], grad_fn=<PowBackward0>)


In [3]:
# dx/dy 
y.backward()
x.grad

tensor([1.9768])

In [4]:

def dy_dx(x):
    return 2*x*t.cos(x**2)
x = t.rand(1, requires_grad=True)
z = dy_dx(x)

In [5]:
z.backward()
x.grad

tensor([1.9583])

### Clearing Gradient

In [6]:
# x.grad.zero_()

### Removing grad disabling gradient tracking.

##### option 1:- requies_grad_(False) <br> option 2:- detach() <br> option 3:- torch.no_grad()

In [7]:
x = t.no_grad(x)
x.grad

AttributeError: 'function' object has no attribute 'grad'