In [17]:
import torch as t
import numpy as np

In [18]:
#Array to Tensors
data = [[1,2],[3,4]]
x_data = t.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [19]:
#from a numpy array
np_array = np.array(data)
x_data = t.tensor(np_array)

In [20]:
x_ones = t.ones((2,3,4))
x_ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [21]:
x_likes_ones = t.ones_like(x_data)
x_likes_ones

tensor([[1, 1],
        [1, 1]])

In [22]:
x_rand = t.rand_like(x_data, dtype=t.float) #overrides the datatype of x_data
x_rand

tensor([[0.1394, 0.0516],
        [0.0666, 0.2540]])

In [23]:
shape = (2,3)
rand_tensor = t.rand(shape)
ones_tensor = t.ones(shape)
zeros_tensor = t.zeros(shape)
rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.3686, 0.0043, 0.2659],
         [0.5096, 0.5824, 0.4283]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [24]:
if t.accelerator.is_available():
    tensor = t.to(t.accelerator.current_accelerator())

In [25]:
tensor = t.ones(4,4)
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [26]:
t1 = t.cat([tensor, tensor, tensor])
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([12, 4])


In [27]:
t1 = t.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


In [28]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y1,y2

(tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]))

In [29]:
y3 = t.rand_like(y1)
print(y3)
print(t.matmul(tensor, tensor.T, out=y3))
y3

tensor([[0.4433, 0.1747, 0.7562, 0.3795],
        [0.1581, 0.3796, 0.4301, 0.9623],
        [0.7606, 0.2981, 0.4291, 0.9418],
        [0.8212, 0.6247, 0.3206, 0.9160]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [30]:
t.manual_seed(3)
tensor = t.rand((4,4))
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = t.rand_like(tensor)
z3 = t.mul(tensor, tensor, out=z3)
z1,z2,z3

(tensor([[1.8178e-05, 1.1145e-02, 8.1706e-02, 7.2656e-04],
         [2.2242e-01, 3.6140e-03, 5.9578e-01, 5.5309e-01],
         [3.5334e-01, 7.8829e-01, 2.0343e-01, 6.3919e-01],
         [2.2452e-02, 1.6118e-01, 2.9351e-03, 2.1105e-01]]),
 tensor([[1.8178e-05, 1.1145e-02, 8.1706e-02, 7.2656e-04],
         [2.2242e-01, 3.6140e-03, 5.9578e-01, 5.5309e-01],
         [3.5334e-01, 7.8829e-01, 2.0343e-01, 6.3919e-01],
         [2.2452e-02, 1.6118e-01, 2.9351e-03, 2.1105e-01]]),
 tensor([[1.8178e-05, 1.1145e-02, 8.1706e-02, 7.2656e-04],
         [2.2242e-01, 3.6140e-03, 5.9578e-01, 5.5309e-01],
         [3.5334e-01, 7.8829e-01, 2.0343e-01, 6.3919e-01],
         [2.2452e-02, 1.6118e-01, 2.9351e-03, 2.1105e-01]]))